tasks:
  - init: >
      python3 -m pip install -r water_monitoring_system/requirements.txt &&
      python3 manage.py water_monitoring_system/migrate

    command: >
      python3 water_monitoring_system/manage.py runserver
github:
    prebuilds:
        pullRequestsFromForks: true