# Generated by Django 2.2.10 on 2020-03-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_auto_20200301_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='longitude',
            field=models.IntegerField(null=True),
        ),
    ]
